Repository acicts/BITS22, pull requests merged in 2022-10, with the labels that each got.

#1 fix: footer responsive issue
  views/css/_main.scss
  views/css/form.css
  views/css/help.css
  views/css/index.css
  views/css/leaderboard.css
  views/css/onlinetests.css
  views/css/profile.css
  views/css/taskdata.css
  views/css/tasks.css
Labels: hacktoberfest-accepted

#2 feat: error page
  views/css/error.css
  views/css/error.scss
  views/error.ejs
Labels: enhancement, hacktoberfest-accepted

#4 Added float animation to index mascot
  views/css/index.css
Labels: hacktoberfest-accepted

#6 fix: minor visual bugs
  views/css/error.css
  views/css/error.scss
  views/css/tasks.css
  views/css/tasks.scss
Labels: hacktoberfest-accepted

#7 update: synced the repo
  routes/admin.js
  routes/index.js
  routes/task.js
  server.js
  views/admin.ejs
  views/analytics.ejs
  views/data.ejs
  views/help.ejs
  views/index.ejs
  views/leaderboard.ejs
  views/onlinetests.ejs
  views/taskdata.ejs
  views/tasks.ejs
Labels: hacktoberfest-accepted

#9 Contribute For Bits 22' Project
  README.md
  Sheet .png
  Spredsheet choose.png
Labels: hacktoberfest-accepted

#11 Added
  views/css/_main.scss
  views/css/analytics.css
  views/css/error.css
  views/css/form.css
  views/css/help.css
  views/css/index.css
  views/css/leaderboard.css
  views/css/onlinetests.css
  views/css/profile.css
  views/css/taskdata.css
  views/css/tasks.css
Labels: hacktoberfest-accepted

#13 Typos and grammar mistakes in main pages!
  views/help.ejs
  views/index.ejs
  views/tasks.ejs
Labels: hacktoberfest-accepted

#15 Update index.ejs
  views/index.ejs
Labels: hacktoberfest-accepted

#16 update: changes in production
  routes/admin.js
  routes/index.js
  routes/task.js
  views/codingpage.ejs
  views/css/_main.scss
  views/css/analytics.css
  views/css/error.css
  views/css/form.css
  views/css/help.css
  views/css/index.css
  views/css/index.scss
  views/css/leaderboard.css
  views/css/onlinetests.css
  views/css/profile.css
  views/css/taskdata.css
  views/css/tasks.css
  views/data.ejs
  views/error.ejs
  views/help.ejs
  views/index.ejs
  views/leaderboard.ejs
  views/login.ejs
  views/onlinetests.ejs
  views/partials/footer.ejs
  views/partials/nav.ejs
  views/partials/profile_taskcat.ejs
  views/partials/taskitem.ejs
  views/signup.ejs
  views/taskdata.ejs
  views/tasks.ejs
  views/tests.ejs
Labels: hacktoberfest-accepted, IMPORTANT

#17 made some mistakes #1
  README.md
Labels: hacktoberfest-accepted

#20 Update help.ejs
  views/help.ejs
Labels: hacktoberfest-accepted, Minor Change

#23 Auto Enable
  routes/task.js
Labels: hacktoberfest-accepted

#22 Auto Enable
  routes/index.js
Labels: hacktoberfest-accepted

#21 Added "How To Enable Competition"
  README.md
Labels: hacktoberfest-accepted
